version: '3.8'
services:
  ongdb-dev:
    container_name: ongdb-dev
    image: graphfoundation/ongdb:3.6
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/Docker/neo4j/data:/data
      - $HOME/Docker/neo4j/logs:/logs
    environment:
      NEO4J_AUTH: neo4j/123456